name: Publish SDK
on: 
  push: 
    tags: 
      - '*.*.*'
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: setup JDK 1.8
      uses: actions/setup-java@v1
      with:
          java-version: 1.8
    - uses: actions/setup-node@v1
      with:
          node-version: 10
    - name: Setup
      run: sh setup.sh
    - name: Install Cocoapods
      run: |
        gem install cocoapods
    - name: Echo current Version
      run: |
        echo ${GITHUB_REF:10}>version
        echo "Current Version is "${GITHUB_REF:10}
    - name: Publish
      run: |
        sh publish.sh
      env:
        COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        BINTARY_USER: ${{ secrets.BINTARY_USER }} 
        BINTARY_REPO: ${{ secrets.BINTARY_REPO }} 
        BINTARY_APIKEY: ${{ secrets.BINTARY_APIKEY }}
    - name: Publish legacy
      run: |
        sh publish-android-legacy.sh
      env:
        BINTARY_USER: ${{ secrets.BINTARY_USER }} 
        BINTARY_REPO: ${{ secrets.BINTARY_REPO }} 
        BINTARY_APIKEY: ${{ secrets.BINTARY_APIKEY }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
